{% set python_min = "3.10" %}
{% set name = "tifffile" %}
{% set version = "2025.5.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 512ad634b142a8aa7e3004f81acb81cd5b0f2ccd16979cb1ef2f01a7fd971bfc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tifffile = tifffile:main
    - tiffcomment = tifffile.tiffcomment:main
    - tiff2fsspec = tifffile.tiff2fsspec:main
    - lsm2bin = tifffile.lsm2bin:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.19.2
    - imagecodecs >=2024.12.30
  run_constrained:
    - matplotlib-base >=3.3
    # zarr3 will now raise a value error
    # those that need tifffile+zarr3 can
    # install the corrrect combination
    # https://github.com/cgohlke/tifffile/pull/296#issuecomment-2869132445
    # - zarr <3

test:
  imports:
    - tifffile
  commands:
    - pip check
    - tifffile --help
    - tiff2fsspec --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cgohlke/tifffile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read and write image data from and to TIFF files.

extra:
  recipe-maintainers:
    - blink1073
    - ericpre
    - jakirkham
    - mrakitin
    - ocefpaf
    - stuarteberg
