{% set version = "0.10.0" %}

package:
  name: tifffile
  version: {{ version }}

source:
  fn: tifffile-{{ version }}.tar.gz
  url: https://github.com/blink1073/tifffile/archive/v{{ version }}.tar.gz
  sha256: 8b3fdabd5368008250b3334711c43f575b7b481ab018b793a6f245ee822f40df

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x

  run:
    - python
    - numpy x.x

test:
  imports:
    - tifffile

about:
  home: https://github.com/blink1073/tifffile
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Read and write image data from and to TIFF files.'

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
    - jakirkham
