{% set python_min = "3.10" %}
{% set name = "tifffile" %}
{% set version = "2025.2.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d731789e691b468746c1615d989bc550ac93cf753e9210865222e90a5a95d11

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tifffile = tifffile:main
    - tiffcomment = tifffile.tiffcomment:main
    - tiff2fsspec = tifffile.tiff2fsspec:main
    - lsm2bin = tifffile.lsm2bin:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.19.2
    - imagecodecs >=2024.12.30
  run_constrained:
    - matplotlib-base >=3.3
    - zarr <3

test:
  imports:
    - tifffile
  commands:
    - pip check
    - tifffile --help
    - tiff2fsspec --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cgohlke/tifffile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read and write image data from and to TIFF files.

extra:
  recipe-maintainers:
    - blink1073
    - ericpre
    - jakirkham
    - mrakitin
    - ocefpaf
    - stuarteberg
