{% set version = "2019.7.26" %}

package:
  name: tifffile
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tifffile/tifffile-{{ version }}.tar.gz
  sha256: 82c5c72de4dc19cc7011e4e8c45492e17121bd02cfa98c015ddd2a83e36f09bc

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - tifffile = tifffile:main
    - lsm2bin = tifffile.lsm2bin:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.11.3
    # require is actually imagecodecs >=2019.5.22, this is a workaround
    - imagecodecs-lite >=2019.4.20
    # remove selector when: https://github.com/conda-forge/futures-feedstock/pull/11
    - futures  # [py27]
    - enum34
    - pathlib

test:
  imports:
    - tifffile

about:
  home: https://github.com/blink1073/tifffile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Read and write image data from and to TIFF files.'

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
    - jakirkham
    - stuarteberg
