{% set name = "tifffile" %}
{% set version = "2022.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 594498345c43a4bb2abb67f0e71c17708059a8f5f5ef1ca70a3416d549c78952

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tifffile = tifffile:main
    - tiffcomment = tifffile.tiffcomment:main
    - tiff2fsspec = tifffile.tiff2fsspec:main
    - lsm2bin = tifffile.lsm2bin:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.19.2
    - imagecodecs >=2021.11.20
  run_constrained:
    - matplotlib-base >=3.3

test:
  imports:
    - tifffile
  commands:
    - pip check
    - tifffile --help
    - tiffcomment --help
    - tiff2fsspec --help
  requires:
    - pip

about:
  home: https://github.com/cgohlke/tifffile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read and write image data from and to TIFF files.

extra:
  recipe-maintainers:
    - blink1073
    - ericpre
    - jakirkham
    - mrakitin
    - ocefpaf
    - stuarteberg
