{% set version = "2020.5.5" %}

package:
  name: tifffile
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tifffile/tifffile-{{ version }}.tar.gz
  sha256: d1d88ce3e74ffa367754a580c40b73e65d4a5c8dc37d7862daaeb72502879fda

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tifffile = tifffile:main
    - lsm2bin = tifffile.lsm2bin:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.15.1
    # require is actually imagecodecs >=2020.1.31, this is a workaround
    - imagecodecs-lite >=2019.4.20

test:
  imports:
    - tifffile

about:
  home: https://github.com/blink1073/tifffile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read and write image data from and to TIFF files.

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
    - jakirkham
    - stuarteberg
