{% set version = "2019.1.1" %}

package:
  name: tifffile
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tifffile/tifffile-{{ version }}.tar.gz
  sha256: 47f98acb206f88e828a4ced08633ba2cfd8db77d9c423ac41b614b6ebd345698

build:
    number: 1000
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - msinttypes  # [win and py<35]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - backports.lzma  # [py27]
    - futures  # [py27]
    - enum34  # [py27]
    - pathlib  # [py27]

test:
  imports:
    - tifffile

about:
  home: https://github.com/blink1073/tifffile
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Read and write image data from and to TIFF files.'

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
    - jakirkham
    - stuarteberg
