schema_version: 1

context:
  python_min: '3.12'
  version: "2026.9.15"

package:
  name: tifffile
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tifffile/tifffile-${{ version }}.tar.gz
  sha256: 2ad086262b5bd3b3804f2d044926e5f63d8f6ae72b235d8b774f164b79f587c4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - tifffile = tifffile:main
      - tiffcomment = tifffile.tiffcomment:main
      - tiff2fsspec = tifffile.tiff2fsspec:main
      - lsm2bin = tifffile.lsm2bin:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2.1
  run_constraints:
    - matplotlib-base >=3.3
    # zarr3 will now raise a value error
    # those that need tifffile+zarr3 can
    # install the corrrect combination
    # https://github.com/cgohlke/tifffile/pull/296#issuecomment-2869132445
    # - zarr <3

tests:
  - python:
      imports:
        - tifffile
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - tifffile --help
      - tiffcomment --help
      - tiff2fsspec --help
      - lsm2bin --help

about:
  summary: Read and write TIFF files
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://www.cgohlke.com
  documentation: https://www.cgohlke.com/docs/tifffile/

extra:
  recipe-maintainers:
    - blink1073
    - ericpre
    - jakirkham
    - mrakitin
    - ocefpaf
    - stuarteberg
