travis:
  secure:
    BINSTAR_TOKEN: rejz0bY5Q9s3WkS/vwn1sgawEZgz5quiDDWx5ZLSIh0P6uSp5j+5GMkRLP+Yqfl32Jym0yiSkeixYwWULwnNtbDtAjUctba7DbJsjOUhe6SS0VlJtlyRBkVG72fYaRta5hxQkiG0YHp9kNmHuDVkgJk/5wAW4o4iY+THKuHxWjqGoBjr/lsssrCrwotuCkc8PS/tztmmGSYvYX9f4091nkkCkMyKTLIXrWGx4gtTzV4c6kayOrQwHBCCVBSE8o8EawQGf6ynhjmxlUHMHKwxJtCEFjXSpLTl9m+XtIUd1O1u0dKkjs1HQzhKukp7uQw/tztEBlw2MpNrVIlEzwL4DRwL53RE80k7LXZ1eDz2WHgAuaUjYiT/NekoBQ/o+DKk4clvt4diYKCi7/AQfTCb5p+0jK1sl42q3tTgLHaAs/cxQ/GXH5thFq5jBWm/+AwigWgacPhBv1NVaqO2kzcQ2yc8kNNrc60RPfcliyAMkLNzFvbqocHuyau1U5luJ1YMr4O2PygQ16XoLI0sV3C/mhl4psMNlEQH8uiGkEjs1dfDjGro/APOEMmJbdZZtIU9rRwMX5NiViNt5l7vu+a11F61qoKK45I6R9xug0Trg9i3bbPtBr6aTnuSDE44NpNepn3ZmL+iyZDe4q98uP/EB4VuwZKcjaVMIPjBombU6pg=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
